2022/09/23 11:33:49 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9001", host: "symfony.localhost"
2022/09/23 11:33:49 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.22.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/23 11:33:52 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.4:9001", host: "symfony.localhost"
2022/09/23 11:39:47 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.4:9001", host: "symfony.localhost"
2022/09/23 11:39:50 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.4:9001", host: "symfony.localhost"
2022/09/23 11:40:33 [error] 7#7: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.4:9001", host: "symfony.localhost"
2022/09/23 11:40:36 [error] 7#7: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.4:9001", host: "symfony.localhost"
2022/09/23 11:45:47 [error] 8#8: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.4:9001", host: "symfony.localhost"
2022/09/23 11:45:50 [error] 8#8: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.4:9001", host: "symfony.localhost"
2022/09/23 11:57:53 [error] 9#9: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.4:9001", host: "symfony.localhost"
2022/09/23 11:57:53 [error] 9#9: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.25.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/23 11:57:56 [error] 9#9: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.4:9001", host: "symfony.localhost"
2022/09/23 11:59:37 [error] 9#9: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.4:9001", host: "symfony.localhost"
2022/09/23 11:59:41 [error] 9#9: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.4:9001", host: "symfony.localhost"
2022/09/23 14:15:21 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:15:21 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/23 14:15:24 [error] 9#9: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:16:47 [error] 9#9: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:16:50 [error] 9#9: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:21:21 [error] 9#9: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:21:24 [error] 9#9: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:22:48 [error] 9#9: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:22:51 [error] 9#9: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:36:02 [error] 9#9: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:49:03 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 14:49:06 [error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9001", host: "symfony.localhost"
2022/09/23 15:07:05 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:07:08 [error] 8#8: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:38:41 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:38:41 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/23 15:38:44 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:48:37 [error] 8#8: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:48:37 [error] 8#8: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/23 15:53:11 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:53:11 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/23 15:53:14 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:54:31 [error] 8#8: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:54:34 [error] 8#8: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:57:09 [error] 8#8: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/23 15:57:12 [error] 8#8: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/24 07:44:23 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/24 07:44:24 [error] 7#7: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/09/24 07:44:26 [error] 7#7: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost"
2022/09/25 10:36:37 [error] 8#8: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.4:9001", host: "symfony.localhost"
2022/10/10 09:46:53 [error] 39#39: *6 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9001", host: "symfony.localhost"
2022/10/10 09:46:53 [error] 39#39: *6 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/10/10 09:46:56 [error] 39#39: *9 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9001", host: "symfony.localhost"
2022/10/10 09:52:43 [error] 41#41: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.localhost/"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130" while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9001", host: "symfony.localhost"
2022/10/10 09:52:43 [error] 41#41: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.localhost/favicon.ico" (from "http://symfony.localhost/")" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130" while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.4:9001", host: "symfony.localhost", referrer: "http://symfony.localhost/"
2022/10/10 09:52:46 [error] 41#41: *4 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://symfony.localhost/"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 130" while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9001", host: "symfony.localhost"
